# Site settings
title: Codependent - Founders and Coders Team
email: adamkowalczyk@gmail.com #team email?
description: > # this means to ignore newlines until "baseurl:"
  Find out who we are and see our work at Founders and Coders.
baseurl: ""
url: "http://codependentfc.github.io"  

# Build settings
markdown: kramdown
